apiVersion: v1
kind: Service
metadata:
  name: {{ include "advanced-deployments.fullname" . }}
  labels:
    {{- include "advanced-deployments.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "advanced-deployments.selectorLabels" . | nindent 4 }}
    {{ toYaml .Values.currentTarget | nindent 4 }}
    #currentTarget needs to be added to values.yaml file. This is what will tell the setup which is current traffic target.